### ISSUE TITLE
Current Feature Requests

### ISSUE THREAD

**Issue by JackMorrissey** [JackMorrissey/beyond-rule-4#4]
Initial feedback from [forum post ](https://support.youneedabudget.com/t/632bml/beyond-rule-4-open-sourced-angular-bootstrap-etc):

- [ ] Select month or range of months to get average budgeted amounts (Moved to #11 )
- [x] More control over which categories count as what
- [x] Rename "Interest Gains" to "Returns" #5

--
- [x] Budget Selector (email 2/12/19) 
  - It's currently using the "last-used" budget.
- [x] Allow Account values to be changed with metadata similar to how categories can be changed (email 2/13/19)
- [x] Quick instructions on how to de-authorize if desired (email 2/15/19)
- [ ] Modifiers for budget required at retirement - External Contributions, Percent Modifier (Moved to #12 )

**Comment by DanielMSchmidt** [comment]
I would like to add an option to have "external contributions", because I live in germany and we get retirement benefits from our country, so my FIRE amount is lower then calculated

**Comment by JackMorrissey** [comment]
Hey @DanielMSchmidt, thanks for the request! To clarify, are these benefits contributions to your account in the accumulation phase, or as a pension for retirees? My quick attempt at understanding German social security makes me think the latter. 

If that's the case, would you anticipate seeing something like:

> With annual expenses of 40,148.52, we're aiming for a Net Worth of 1,003,713.

changing to

> With annual expenses of 40,148.52, and expected external annual contributions of 12,000, we're aiming for a Net Worth of 703,713.

Does that align with what you're thinking? 

If yes, could we also solve this generically by putting a percentage modifier for the final annual expenses amount?

> With annual expenses of 36,133.67 (90% of 40,148.52), we're aiming for a Net Worth of 90,3341.7.

With the second approach, that'd also be useful for people playing around with modifying their current lifestyle or what they expect it to change in retirement. It'd be great if that solves your scenario as well.

**Comment by DanielMSchmidt** [comment]
I like the "external contributions" approach, I can guestimate the number I will be getting from the government on a yearly basis. Changing it with a modifier is a bit more work for me as a user, but that should be fine :)

**Comment by DanielMSchmidt** [comment]
Besides, having more control over the categories that count as retirement would be cool, my budget is in German 🇩🇪

**Comment by JackMorrissey** [comment]
Sound good. I'll add it to the list. Thanks.

**Comment by JackMorrissey** [comment]
Hey @DanielMSchmidt, I worked on this a bunch last night and although I haven't tackled "External Contributions" yet, I revamped the "Net Worth" section with overrides and put in more flexibility over picking categories that count as contributions. 

You can now just throw `BR4 +` in the notes of a category to use the value in YNAB to count as a contribution regardless of the name of the category group. (You can also manually set it with `BR4 + <amount>`)

I think I'll close out this issue and move the feature request for External Contributions to a new issue to keep everything split up.

**Comment by JackMorrissey** [comment]
Closing! Please put any new feature requests in new issues.
